### ISSUE TITLE
Actualizando state no inmediato

### ISSUE THREAD

**Issue by pedroaragon360** [zamarrowski/Curso-React-Redux#6]
Hola!

Estaba trabajando con el LocalStorage, y en una función de añadir item actualizo el state:

```
            this.setState({cart: [...this.state.cart,{id:addProduct.id,units:1}]})
            console.log(this.state.cart)
```
Pero curiosamente cuando imprimo a continuación el valor de state me devuelve el estado anterior, la solución parece ser esta:

```
            let newCart = [...this.state.cart,{id:addProduct.id,units:1}]
            this.setState({cart: newCart})
            console.log(newCart)
```

Me gustaría saber a que se debe, gracias!

**Comment by zamarrowski** [comment]
La actualización del estado es asíncrona por lo que cuando lo imprimes por pantalla saca el estado anterior. Puedes pasarle un callback como segundo parámetro a la función setState para que lo imprima cuando haya terminado.
